# Generated by Django 2.2 on 2019-11-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projekty',
        ),
    ]
